Satellite page improvements
griush/GalileoHack pull request #30
Opened 2024-08-11 22:19 UTC by marticliment

Improvements to the satellites page

2024-08-17 19:24 UTC, marticliment commented
@griush, si vols es pot posar un timer per a que les dades es carreguin cada x milisegons. És com està implementada la part dels satèl·lits

2024-08-18 15:47 UTC, griush commented
no es mala

2024-08-27 11:43 UTC, marticliment commented
@griush prova si el mixed provider et funciona, que és android 12+

2024-08-27 13:27 UTC, griush requested changes
es veu be, hem de mirar que s'actualitzi la ubicacio amb un TImer pq de moment sembla que nomes s'actualiza quan canvies de fragment i tornes

2024-08-27 13:39 UTC, marticliment commented
Nono el mapa la va actualitzant sol, però a vegades costa de veure

2024-08-27 13:49 UTC, griush commented
a vale

2024-08-27 13:49 UTC, griush approved these changes
palante

2024-08-27 13:49 UTC, merged

2024-08-27 13:51 UTC, griush commented
@marticliment queda fer lo que hi ha a issues